---
- name: Deploy Dockerized Website
  hosts: web
  vars:
    ansible_ssh_private_key_file: "{{ ansible_private_key }}"  # SSH private key to access EC2 instance
  tasks:
    - name: Ensure Docker is installed
      become: yes
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Start Docker service
      become: yes
      service:
        name: docker
        state: started
        enabled: yes

    - name: Pull Docker image from Docker Hub
      docker_image:
        name: demonharsh124/website
        tag: "{{ git_hash }}"  # Use git_hash passed from Jenkins or a default value
        source: pull

    - name: Stop and remove any running container with the same name
      docker_container:
        name: website
        state: absent
        force: yes  # Ensure the container is stopped and removed

    - name: Run the Docker container
      docker_container:
        name: website
        image: demonharsh124/website:{{ git_hash }}
        state: started
        restart_policy: always
        published_ports:
          - "80:80"
