- name: Deploy Dockerized Website
  hosts: web
  become: true
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    docker_user: "{{ lookup('env', 'DOCKER_USER') }}"
    docker_pass: "{{ lookup('env', 'DOCKER_PASS') }}"
    image_name: "websiteimage"
    commit_hash: "{{ image_tag | default('latest') }}"

  tasks:
    - name: Remove conflicting containerd package
      apt:
        name: containerd
        state: absent
      ignore_errors: yes

    - name: Update package lists
      apt:
        update_cache: yes

    - name: Check if there are any held packages
      shell: dpkg --get-selections | grep hold
      register: held_packages
      ignore_errors: yes

    - name: Debug held packages
      debug:
        msg: "{{ held_packages.stdout_lines }}"

    - name: Unhold any held packages
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - containerd
        - docker.io
      when: held_packages.stdout_lines | length > 0

    - name: Resolve held packages if any
      apt:
        state: latest
        pkg: "{{ held_packages.stdout_lines | map('regex_replace', ' hold', '') | list }}"
      when: held_packages.stdout_lines | length > 0

    - name: Ensure required packages are installed
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - docker.io
        state: present
        update_cache: yes
      register: install_packages

    - name: Ensure Docker service is running
      service:
        name: docker
        state: started
        enabled: true

    - name: Log in to Docker Hub
      docker_login:
        username: "{{ docker_user }}"
        password: "{{ docker_pass }}"

    - name: Pull Docker image
      docker_image:
        name: "{{ docker_user }}/{{ image_name }}"
        tag: "{{ commit_hash }}"
        source: pull
        state: present

    - name: Stop existing website container
      docker_container:
        name: website
        state: absent
        force_kill: yes

    - name: Run new website container
      docker_container:
        name: website
        image: "{{ docker_user }}/{{ image_name }}:{{ commit_hash }}"
        state: started
        ports:
          - "80:80"
        restart_policy: always
