---
- name: Deploy Website to EC2
  hosts: web
  vars:
    git_hash: "{{ git_hash }}"  # Receives the git hash passed from Jenkins
  tasks:
    - name: Ensure Docker is installed
      become: yes
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Pull Docker image from Docker Hub
      docker_image:
        name: demonharsh124/website
        tag: "{{ git_hash }}"
        source: pull

    - name: Stop and remove any running container with the same name
      docker_container:
        name: website
        state: absent
        force_kill: yes  # Ensure container is stopped and removed, forcefully if needed

    - name: Run the Docker container
      docker_container:
        name: website
        image: demonharsh124/website:{{ git_hash }}
        state: started
        restart_policy: always
        published_ports:
          - "80:80"
