- name: Deploy Dockerized Website
  hosts: web
  become: true
  vars:
    docker_user: "{{ lookup('env', 'DOCKER_USER') }}"
    docker_pass: "{{ lookup('env', 'DOCKER_PASS') }}"
    image_name: "websiteimage"
    commit_hash: "{{ image_tag | default('latest') }}"

  tasks:
    - name: Ensure required packages are installed
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - docker.io
        state: present
        update_cache: yes

    - name: Ensure Docker service is running
      service:
        name: docker
        state: started
        enabled: true

    - name: Log in to Docker Hub
      docker_login:
        username: "{{ docker_user }}"
        password: "{{ docker_pass }}"

    - name: Pull Docker image
      docker_image:
        name: "{{ docker_user }}/{{ image_name }}"
        tag: "{{ commit_hash }}"
        source: pull
        state: present

    - name: Stop existing website container
      docker_container:
        name: website
        state: absent
        force_kill: yes

    - name: Run new website container
      docker_container:
        name: website
        image: "{{ docker_user }}/{{ image_name }}:{{ commit_hash }}"
        state: started
        ports:
          - "80:80"
        restart_policy: always